// <auto-generated />
namespace _07_linq与EF框架.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class v3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3));
        
        string IMigrationMetadata.Id
        {
            get { return "202608261351418_v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
